name: Publish CodeQL packs

on:
  release:
    types: [published]

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: trailofbits/setup-codeql@615e3864087261d42cce229e3eec419ab9b22c36 # main
        with:
          version: '2.25.1'
          platform: 'linux64'
          checksum: '4f070e6cc7009e75aec307ed109c2fcf0501e579c20a31080b893e31209523d5'
      - run: make test
      - run: make publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
