name: CodeQL queries test

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: trailofbits/setup-codeql@615e3864087261d42cce229e3eec419ab9b22c36 # main
        with:
          version: '2.25.1'
          platform: 'linux64'
          checksum: '4f070e6cc7009e75aec307ed109c2fcf0501e579c20a31080b893e31209523d5'
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - run: make format-check
      - run: make test
      - name: Verify doc/QUERIES.md is up to date
        run: |
          make generate-table
          git diff --exit-code doc/QUERIES.md
