name: CodeQL queries test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: trailofbits/setup-codeql@main
        with:
          version: '2.25.1'
          platform: 'linux64'
          checksum: '4f070e6cc7009e75aec307ed109c2fcf0501e579c20a31080b893e31209523d5'
      - run: make format-check
      - run: make test
